# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(choices=[(datetime.time(9, 0), '9:00am'), (datetime.time(9, 30), '9:30am'), (datetime.time(10, 0), '10:00am'), (datetime.time(10, 30), '10:30am'), (datetime.time(11, 0), '11:00am'), (datetime.time(11, 30), '11:30am'), (datetime.time(12, 0), '12:00pm'), (datetime.time(12, 30), '12:30pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(13, 30), '1:30pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(14, 30), '2:30pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(15, 30), '3:30pm'), (datetime.time(16, 0), '4:00pm'), (datetime.time(16, 30), '4:30pm')])),
                ('end_time', models.TimeField(choices=[(datetime.time(9, 30), '9:30am'), (datetime.time(10, 0), '10:00am'), (datetime.time(10, 30), '10:30am'), (datetime.time(11, 0), '11:00am'), (datetime.time(11, 30), '11:30am'), (datetime.time(12, 0), '12:00pm'), (datetime.time(12, 30), '12:30pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(13, 30), '1:30pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(14, 30), '2:30pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(15, 30), '3:30pm'), (datetime.time(16, 0), '4:00pm'), (datetime.time(16, 30), '4:30pm'), (datetime.time(17, 0), '5:00pm')])),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
            ],
        ),
    ]
