# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-07 09:27
from __future__ import unicode_literals

import accounts.managers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApproveTestResultNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('Infectious Disease', 'Infectious Disease'), ('Traumatic Injury', 'Traumatic Injury'), ('Poisoning/Drugs', 'Poisoning/Drugs'), ('Cardiac Issues', 'Cardiac Issues'), ('Chronic Illness', 'Chronic Illness'), ('Surgery', 'Surgery'), ('Other', 'Other')], max_length=50)),
                ('admission_details', models.CharField(blank=True, max_length=256)),
                ('discharge_details', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OngoingTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_hospital', to='accounts.Hospital')),
                ('src_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_hospital', to='accounts.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiveTransferNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.IntegerField()),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='RemovedPrescriptionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='TestResultNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('max_patients', models.IntegerField()),
                ('hospitals', models.ManyToManyField(to='accounts.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='H_Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('insurance_number', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10)),
                ('isInHospital', models.BooleanField(default=False)),
                ('isInTransit', models.BooleanField(default=False)),
                ('emergency_first_name', models.CharField(blank=True, max_length=30)),
                ('emergency_last_name', models.CharField(blank=True, max_length=30)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=16)),
                ('emergency_address', models.CharField(blank=True, max_length=200)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='admit_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='discharge_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital'),
        ),
        migrations.AddField(
            model_name='approvetestresultnotification',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification'),
        ),
        migrations.AddField(
            model_name='appointmentnotification',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='ongoingtransfer',
            name='dest_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_doctor', to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='ongoingtransfer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
        migrations.AddField(
            model_name='ongoingtransfer',
            name='src_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_doctor', to='accounts.Doctor'),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nurses',
            field=models.ManyToManyField(to='accounts.Nurse'),
        ),
    ]
